--usuario

INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, PAIS_NACIMIENTO) VALUES ('PEREZ', '1', 'ROBERTO', '093939393', true, 'CR');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, PAIS_NACIMIENTO) VALUES ('SANCHEZ', '2', 'RAUL', '093223333', true, 'CR');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, PAIS_NACIMIENTO) VALUES ('SANCHEZ PAZMINO', '11', 'PATRICIO', '092222', true, 'CR');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, PAIS_NACIMIENTO) VALUES ('SANCHEZ SALAZAR', '111', 'MAURICIO', '0933333', true, 'CR');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, PAIS_NACIMIENTO) VALUES ('SANCHEZ SALAZAR', '1111', 'HORACIO', '0934555', true, 'HN');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, PAIS_NACIMIENTO) VALUES ('DOE', '1111', 'JOHN', '0934555', true, 'GT');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, PAIS_NACIMIENTO) VALUES ('SHOW', '1100', 'JOHN', '0937566757', true, 'BR');

INSERT INTO DIRECCION (NOMBRE, NOMENCLATURA, CLIENTE_ID) VALUES ('CIUDAD', 'C1', 1);
INSERT INTO DIRECCION (NOMBRE, NOMENCLATURA, CLIENTE_ID) VALUES ('CIUDAD', 'C1', 2);

INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('123', 'EFEC', 1, true);
INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('456', 'EFEC', 1, true);
INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('789', 'EFEC', 1, false);
INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('456', 'EFEC', 2, false);
INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('789', 'EFEC', 5, true);

INSERT INTO TARJETA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('123', 'EFEC', 5, true);
INSERT INTO TARJETA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('456', 'EFEC', 6, false);
INSERT INTO TARJETA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('987', 'EFEC', 6, true);
INSERT INTO TARJETA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('348', 'EFEC', 7, false);
INSERT INTO TARJETA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('984', 'EFEC', 1, true);

INSERT INTO INVERSION (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('123', 'EFEC', 5, true);