--usuario

INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO) VALUES ('PEREZ', '1', 'ROBERTO', '093939393', true);
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO) VALUES ('SANCHEZ', '2', 'RAUL', '093223333', true);
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO) VALUES ('SANCHEZ PAZMINO', '11', 'PATRICIO', '092222', true);
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO) VALUES ('SANCHEZ SALAZAR', '111', 'MAURICIO', '0933333', true);
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO) VALUES ('SANCHEZ SALAZAR', '1111', 'HORACIO', '0934555', true);