--usuario

INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, CODIGO_PAIS) VALUES ('PEREZ', '1', 'ROBERTO', '093939393', true, 'CR');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, CODIGO_PAIS) VALUES ('SANCHEZ', '2', 'RAUL', '093223333', true, 'CR');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, CODIGO_PAIS) VALUES ('SANCHEZ PAZMINO', '11', 'PATRICIO', '092222', true, 'CR');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, CODIGO_PAIS) VALUES ('SANCHEZ SALAZAR', '111', 'MAURICIO', '0933333', true, 'CR');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, ESTADO, CODIGO_PAIS) VALUES ('SANCHEZ SALAZAR', '1111', 'HORACIO', '0934555', true, 'CR');

INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ACTIVA) VALUES ('123', 'EFEC', 1, true);
INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ACTIVA) VALUES ('456', 'EFEC', 1, true);
INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ACTIVA) VALUES ('789', 'EFEC', 2, true);